### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by dollebrekel** [Snipa22/node-multi-hashing-aesni#3]
I am trying to get the multi-node hashing working on Linux.
I installed the NMP on my controller. but how do I startup with multi-node hashing? and where can I enter my credentials such as pool info, wallet address, etc? also, how can I choose an algorithm to mine? 

I cant find a clear explanation on GitHub about this. I hope you could help me with this issue.

**Comment by Snipa22** [comment]
This is not for mining.  This is to provide hashing functionality to other software that does mining.
